version: '3'
services:
  messstellenbetreiber1:
    build: ./smart-meter-messstellenbetreiber
    ports:
      - "9001:5000"
    expose:
      - 9001
    networks:
      - internet
    extra_hosts:
      - "host.docker.internal:host-gateway"
  stromzaehler1:
    build: ./smart-meter-stromzaehler
    ports:
      - "5001:5000"
    expose:
      - 5001
    volumes:
      - ./smart-meter-stromzaehler/src/.env-1:/python-docker/src/.env
    #  - 5001-5010:5000
    #deploy:
    #  replicas: 10
    networks:
      - internet
    depends_on:
      - messstellenbetreiber1
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  internet:
# https://stackoverflow.com/questions/56203272/docker-compose-scaling-with-unique-environment-variable