version: "3"
services:
  messstellenbetreiber1:
    build: ./smart-meter-messstellenbetreiber
    ports:
      - "9001:5000"
    expose:
      - 9001
    networks:
      - internet
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FLASK_DEBUG=1
  stromzaehler1:
    build: ./smart-meter-stromzaehler
    volumes:
      - ./smart-meter-stromzaehler/generated/.env-1:/python-docker/res/.env
      - ./smart-meter-stromzaehler/generated/database-1.db:/python-docker/res/database.db
    #  - 5001-5010:5000
    #deploy:
    #  replicas: 10
    networks:
      - internet
    depends_on:
      - messstellenbetreiber1
    extra_hosts:
      - "host.docker.internal:host-gateway"
  stromzaehler2:
    build: ./smart-meter-stromzaehler
    volumes:
      - ./smart-meter-stromzaehler/generated/.env-2:/python-docker/res/.env
      - ./smart-meter-stromzaehler/generated/database-2.db:/python-docker/res/database.db
    networks:
      - internet
    depends_on:
      - messstellenbetreiber1
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  internet:
# https://stackoverflow.com/questions/56203272/docker-compose-scaling-with-unique-environment-variable
