version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - kundenportal
  kundenportal:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - db
    links:
      - db:database
    networks:
      - kundenportal
      - internet
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
  prisma_to_db:
    build: .
    depends_on:
      - kundenportal
      - db
    networks:
      - kundenportal
    links:
      - db:database
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
    command: pnpm prisma db push

networks:
  kundenportal:
    name: kundenportal
  internet:
    external: true
